export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTAL_BY_ID = 'FETCTH_RENTAL_BY_ID';
export const FETCH_RENTAL_BY_ID_SUCCESS = 'FETCTH_RENTAL_BY_ID_SUCCESS';
export const FETCH_RENTAL_BY_ID_INIT = 'FETCTH_RENTAL_BY_ID_INIT';
